from 172.23.108.38/python:3.10-slim

RUN python -m pip install --index-url http://172.23.108.28 --trusted-host 172.23.108.28 mkdocs-material mkdocs-static-i18n mdx-include mkdocs-markdownextradata-plugin