site_name: Propan
site_description: Propan is a modern framework for building Applications based on Messaging Architecture.
site_url: https://lancetnik.github.io/Propan/
dev_addr: 0.0.0.0:8000

repo_name: lancetnik/propan
repo_url: https://github.com/lancetnik/propan
edit_uri: https://github.com/lancetnik/propan

copyright: Copyright &copy; 2019 - 2023 Pastukhov Nikita

docs_dir: docs

extra_css:
  - assets/stylesheets/termynal.css
  - assets/stylesheets/custom.css

extra_javascript:
  - assets/javascripts/termynal.js
  - assets/javascripts/custom.js

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - content.code.annotate
    - navigation.path
    - navigation.top
  i18n:
    prev: 'Previous'
    next: 'Next'
  icon:
    repo: fontawesome/brands/github
  logo: assets/img/logo-white.png
  favicon: assets/img/favicon.png

plugins:
  - search
  - glightbox
  - macros:
      include_dir: includes
  - i18n:
      default_language: en
      docs_structure: folder
      material_alternate: true
      languages:
        en:
          name: English
          build: true
        ru:
          name: Русский
          build: true

markdown_extensions:  # do not reorder
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      guess_lang: false
  - mdx_include:
      base_path: .
  - footnotes
  - tables
  - admonition
  - codehilite
  - extra
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format ''
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji ""
      emoji_generator: !!python/name:materialx.emoji.to_svg ""
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

extra:
  analytics:
    provider: google
    property: G-5WCRLZHPSD
  urls:
    fastapi: https://fastapi.tiangolo.com/ru/
    redis: https://redis.readthedocs.io/en/stable/index.html
    aio_pika: https://aio-pika.readthedocs.io/en/latest/
    pika: https://pika.readthedocs.io/en/stable/
    aiokafka: https://aiokafka.readthedocs.io/en/stable/
    aiobotocore: https://aiobotocore.readthedocs.io/en/latest/
    nats_py: https://github.com/nats-io/nats.py
    pydantic: https://docs.pydantic.dev/
    pytest: https://docs.pytest.org/en/latest/
    asyncapi: https://www.asyncapi.com/
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/lancetnik/propan
    - icon: simple/telegram
      link: https://t.me/propan_python

nav:
  - Welcome: index.md
  - Getting Started:
    - Hello, Propan!: getting_started/1_quick-start.md
    - CLI Tool: getting_started/2_cli.md
    - Application: getting_started/3_app.md
    - Brokers:
      - Basics: getting_started/4_broker/1_index.md
      - Routing and Errors: getting_started/4_broker/2_routing.md
      - Incoming Messages: getting_started/4_broker/3_type-casting.md
      - Custom Serialization: getting_started/4_broker/4_custom_serialization.md
      - Publish Messages: getting_started/4_broker/5_publishing.md
      - RPC over MQ: getting_started/4_broker/6_rpc.md
    - Dependency Injection:
      - Depends: getting_started/5_dependency/1_di-index.md
      - Context: getting_started/5_dependency/2_context.md
    - Lifespan: getting_started/6_lifespans.md
    - Testing: getting_started/7_testing.md
    - Logging: getting_started/8_logging.md
    - Documentation: getting_started/9_documentation.md
  - RabbitMQ:
    - Routing: rabbit/1_routing.md
    - Exchanges: rabbit/2_exchanges.md
    - Queues and Bindings: rabbit/3_queues.md
    - Rabbit Publishing: rabbit/4_publishing.md
    - Examples:
      - Direct Exchange: rabbit/5_examples/1_direct.md
      - Fanout Exchange: rabbit/5_examples/2_fanout.md
      - Topic Exchange: rabbit/5_examples/3_topic.md
      - Header Exchange: rabbit/5_examples/4_header.md
  - Redis Pub/Sub:
    - Redis Basics: redis/1_redis-index.md
    - Redis Publishing: redis/2_publishing.md
    - Examples:
      - Direct: redis/3_examples/1_direct.md
      - Pattern: redis/3_examples/2_pattern.md
  - Kafka:
    - Kafka Basics: kafka/1_kafka-index.md
  - SQS:
    - SQS Basics: sqs/1_sqs-index.md
  - Nats:
    - Nats Basics: nats/1_nats-index.md
    - Nats Publishing: nats/2_publishing.md
    - Examples:
      - Direct: nats/3_examples/1_direct.md
      - Pattern: nats/3_examples/2_pattern.md
    - NatsJS: nats/4_nats-js.md
  - Integrations: integrations/1_integrations-index.md
  - FastAPI Plugin: integrations/2_fastapi-plugin.md  
  - Contributing:
    - TODOS: contributing/1_todo.md
    - Environment: contributing/2_contributing-index.md
    - Documentation: contributing/3_docs.md
    - Adapters: contributing/4_adapters.md
  - Alternatives: alternatives.md
  - Help Propan: help.md
  - Release Notes: CHANGELOG.md
