name: Pages

on:
  push:
    branches:
      - main
    paths:
      - docs/**
      - .github/workflows/documentation.yml

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material mkdocs-static-i18n mdx-include mkdocs-macros-plugin
      - working-directory: ./docs
        run: mkdocs gh-deploy --force
